config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  resources :movies, only: [:show] do
    get :search, on: :collection
    post :add_to_favorites, on: :collection
  end
  get 'favorites', to: 'movies#favorites', as: 'favorite_movies'
  resources :favorite_movies, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite_movie.rb
class FavoriteMovie < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorite_movies_controller.rb
class FavoriteMoviesController < ApplicationController

  def destroy
    favorite_movie = FavoriteMovie.find_by(movie_id: params[:id])
    favorite_movie.destroy
    flash[:notice] = 'Movie removed from favorites.'
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    response = HTTParty.get("#{TMDB_BASE_URL}/movie/popular?api_key=#{TMDB_API_KEY}")
    @popular_movies = response.parsed_response['results']

    @movies = Movie.all
  end

  def search
    query = params[:query]
    response = HTTParty.get("#{TMDB_BASE_URL}/search/movie?api_key=#{TMDB_API_KEY}&query=#{query}")
    @search_results = response.parsed_response['results']
  end

  def show
    response = HTTParty.get("#{TMDB_BASE_URL}/movie/#{params[:id]}?api_key=#{TMDB_API_KEY}")
    @movie = response.parsed_response
    render :show
  end

  def add_to_favorites
    movie_id = params[:movie_id]
    if FavoriteMovie.exists?(movie_id: movie_id)
      @added_to_favorites = false
    else
      FavoriteMovie.create(movie_id: movie_id)
      @added_to_favorites = true
    end
    puts "@added_to_favorites: #{@added_to_favorites}"
    redirect_back(fallback_location: root_path)
  end


  def favorites
    favorite_movie_ids = FavoriteMovie.pluck(:movie_id)
    @favorite_movies = favorite_movie_ids.map { |movie_id| fetch_movie(movie_id) }
  end

  private

  def fetch_movie(movie_id)
    response = HTTParty.get("#{TMDB_BASE_URL}/movie/#{movie_id}?api_key=#{TMDB_API_KEY}")
    response.parsed_response
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_movies_helper.rb
module FavoriteMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def added_to_favorites?(movie_id)
    FavoriteMovie.exists?(movie_id: movie_id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moviedb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/favorites.html.erb
<div class="content-container">
  <h1 class="text-center">Favorite Movies</h1>
  <div class="movie-container">
    <% if @favorite_movies.any? %>
      <% @favorite_movies.each do |movie| %>
        <div class="movie">
          <% if movie['poster_path'].present? %>
            <%= link_to movie_path(movie['id']) do %>
              <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'] %>
            <% end %>
          <% else %>
            <%= image_tag 'default_poster.jpg', alt: 'No Poster Available' %>
          <% end %>
          <h3 class="movie-title">
            <%= link_to movie['title'], movie_path(movie['id']) %>
          </h3>
          <%= button_to 'Remove from Favorites', favorite_movie_path(id: movie['id']), method: :delete, data: { confirm: 'Are you sure you want to remove this movie from your favorites?' }, class: 'remove-from-favorites-button' %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center no-movies-message">No favorite movies added yet.</p>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="content-container">
  <div class="favorite-movies-link">
    <%= link_to 'Favorite Movies', favorite_movies_path %>
  </div>
  <h1 class="text-center">Latest Movies</h1>

  <%= form_tag search_movies_path, method: :get, class: "search-form" do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search for a movie" %>
    <%= submit_tag "Search" %>
  <% end %>

  <div class="movie-container">
    <% if @popular_movies.any? %>
      <% @popular_movies.each do |movie| %>
        <div class="movie">
          <% if movie['poster_path'].present? %>
            <%= link_to movie_path(movie['id']) do %>
              <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'] %>
            <% end %>
          <% else %>
            <%= image_tag 'default_poster.jpg', alt: 'No Poster Available' %>
          <% end %>
          <h3 class="movie-title">
            <%= link_to movie['title'], movie_path(movie['id']) %>
          </h3>
          <%= button_to added_to_favorites?(movie['id']) ? 'Added to Favorites' : 'Add to Favorites', add_to_favorites_movies_path(movie_id: movie['id']), remote: true, class: 'add-to-favorites-button', data: { movie_id: movie['id'] } %>
        </div>
      <% end %>
    <% else %>
      <p>No popular movies data available.</p>
    <% end %>
  </div>
</div>

app/views/movies/search.html.erb
<div class="content-container">
  <h1 class="text-center">Search Results</h1>
  <div class="movie-container">
    <% if @search_results.present? %>
      <% @search_results.each do |movie| %>
        <div class="movie">
          <% if movie['poster_path'].present? %>
            <%= link_to movie_path(movie['id']) do %>
              <%= image_tag "https://image.tmdb.org/t/p/w500#{movie['poster_path']}", alt: movie['title'] %>
            <% end %>
          <% else %>
            <%= image_tag 'default_poster.jpg', alt: 'No Poster Available' %>
          <% end %>
          <h3 class="movie-title">
            <%= link_to movie['title'], movie_path(movie['id']) %>
          </h3>
          <%= button_to added_to_favorites?(movie['id']) ? 'Added to Favorites' : 'Add to Favorites', add_to_favorites_movies_path(movie_id: movie['id']), remote: true, class: 'add-to-favorites-button', data: { movie_id: movie['id'] } %>
        </div>
      <% end %>
    <% else %>
      <p>No search results found.</p>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="content-container">
  <div class="movie-details">
    <h1 class="text-center"><%= @movie['title'] %></h1>
    <% if @movie['poster_path'].present? %>
      <%= image_tag "https://image.tmdb.org/t/p/w500#{@movie['poster_path']}", alt: @movie['title'] %>
    <% else %>
      <%= image_tag 'default_poster.jpg', alt: 'No Poster Available' %>
    <% end %>
    <p class="movie-overview"><%= @movie['overview'] %></p>
    <p class="release-date">Release Date: <%= @movie['release_date'] %></p>
  </div>
</div>